version: "3.8"
services:
  application:
    container_name: github-actions-application
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    environment:
      - GIN_MODE=release
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge